### ISSUE TITLE
Undefined libconv when build on Linux

### ISSUE THREAD

**Issue by christopherwoo** [opentoonz/opentoonz#2467]
### Issue Summary

When build on Ubuntu 18.04, it failed for "undefined reference to libiconv".

### Screenshot or Video Reference

```
[ 81%] Linking CXX executable ../bin/OpenToonz
../lib/opentoonz/libtnzstdfx.so: undefined reference to `libiconv_open'
../lib/opentoonz/libtnzstdfx.so: undefined reference to `libiconv_close'
../lib/opentoonz/libtnzstdfx.so: undefined reference to `libiconv'
```
### Steps to Reproduce

cd toonz/build
cmake ../sources
make

### Expected Results

something but not "undefined reference"

### Actual Results

```
[ 81%] Linking CXX executable ../bin/OpenToonz
../lib/opentoonz/libtnzstdfx.so: undefined reference to `libiconv_open'
../lib/opentoonz/libtnzstdfx.so: undefined reference to `libiconv_close'
../lib/opentoonz/libtnzstdfx.so: undefined reference to `libiconv'
collect2: error: ld returned 1 exit status
toonz/CMakeFiles/OpenToonz.dir/build.make:9972: recipe for target 'bin/OpenToonz' failed
make[2]: *** [bin/OpenToonz] Error 1
CMakeFiles/Makefile2:1018: recipe for target 'toonz/CMakeFiles/OpenToonz.dir/all' failed
make[1]: *** [toonz/CMakeFiles/OpenToonz.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```
### System Information
* **OpenToonz Version**: git commit 01e9518533aff5d76defc8b0b487c03e87bf1417
* **Operating System**: Ubuntu 18.04
* **CPU**: x86_64/Intel
* **Memory**: ４GB
* **Graphics Card**: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller 
* **Graphics Tablet**: none

**Comment by rozhuk-im** [comment]
This commit remove unused iconv dep from code and should fix this issue: https://github.com/opentoonz/opentoonz/pull/3231/commits/bdac84a72d513a16394dbc3163c05b711e689a4c

**Comment by rozhuk-im** [comment]
PR: https://github.com/opentoonz/opentoonz/pull/3304
