### PR TITLE
ci(build): update CMake to 3.5 and fix macOS build issues

### PR DESCRIPTION
**Pull request by andeon**
- Bump minimum CMake version to 3.5
- Adjust build flags and paths for compatibility in CMakeLists.txt
- Refactor post-build steps for macOS (RPATH, Info.plist, portability)
- Fix deprecated uint32/uint16 warnings in tiio_tif.cpp to support macOS build

Additional minor updates:
- Update Windows and Appveyor GitHub workflows
- Fix macOS build: add openjph and openexr (missing dylib after Homebrew update)

### CODE REVIEW

**Comment by andeon** [comment]
The first PR has an issue because AppVeyor is using Visual Studio 2022, but the Qt version being searched for is built with MSVC 2019. So I had to revert to Visual Studio 2019 to test it, and it worked.

If switching to Visual Studio 2022 is necessary, then the Qt path should also be updated to the 2022 version. It seems the older CMake configuration doesn’t check this properly. Since I haven’t tested this setup, I’m leaving it as is for now. If someone could test Qt 2022 with Visual Studio 2022 to verify it works, we could update it again. 

Also, we need to check why AppVeyor isn’t using the Qt patch from @shun-iwasawa.

- [x]  **Done!** ~~I'll squash the commits to clean things up. There's no way to test AppVeyor before sending the pull request, so please don’t merge it yet.~~

Need to spot some issues related, because I think this PR too resolves them such as #3593 by fixing compilation errors (e.g., type mismatches in libtiff calls) in tiio_tif.cpp, without any loss of functionality. To validate and ensure there is no regression, it's important to check some TIFF files and compare.

**Comment by xavier2k6** [comment]
AppVeyor have included newer (Boost 1.87, 1.88, 1.89) in 2019/2022 images
https://www.appveyor.com/updates/

**Comment by xavier2k6** [comment]
Why didn't you update minimum CMake to `3.10+`?  xref.: #5834, also https://github.com/opentoonz/opentoonz/issues/5754#issuecomment-3288007733

EDIT:
https://cmake.org/cmake/help/latest/release/3.31.html#deprecated-and-removed-features

**Comment by RodneyBaker** [comment]
For reference of what @manongjohn is doing regarding Mac OS over in Tahoma2D:  https://github.com/tahoma2d/tahoma2d/pull/1909

**Comment by xavier2k6** [comment]
https://github.com/opentoonz/opentoonz/blob/3f2991eb9cd8dc062405de826bfbc2b7e0c210d8/.github/workflows/CMakeLists.txt#L1

**Comment by andeon** [comment]
> Why didn't you update minimum CMake to `3.10+`? xref.: #5834, also [#5754 (comment)](https://github.com/opentoonz/opentoonz/issues/5754#issuecomment-3288007733)
> 
> EDIT: https://cmake.org/cmake/help/latest/release/3.31.html#deprecated-and-removed-features

@xavier2k6 It's a slow-moving process, and I'm taking a more conservative approach. I tested with CMake 3.5, and it might also work with 3.10. However, the main priority right now is to stabilize development so we can properly test the builds and users can start receiving the improvements. It took days of testing, tweaking, and figuring things out just to get this working. I'll need to check later if it actually works with 3.10, so it could possibly be updated in the future.

> https://github.com/opentoonz/opentoonz/blob/3f2991eb9cd8dc062405de826bfbc2b7e0c210d8/.github/workflows/CMakeLists.txt#L1

I have no idea why this CMakeLists.txt file is located in .github/workflows/. Most likely, that file is misplaced.

> For reference of what @manongjohn is doing regarding Mac OS over in Tahoma2D: [tahoma2d/tahoma2d#1909](https://github.com/tahoma2d/tahoma2d/pull/1909)

@RodneyBaker I considered this as well, but I preferred to start by trying to solve the problem more definitively. Also, in that case, I would need to check and find out if there is a way to fix some configuration on AppVeyor to ensure it works there as well.

**Comment by RodneyBaker** [comment]
@andeon When in doubt I prefer the conservative approach.
That doesn't mean I always take that path but I definitely prefer it.

You all are doing great at keeping us moving ahead and where we run into roadbumps you've always come through to get us back on track.

Much appreciated.

I'm of the mind to merge this PR for the good it will do but I know we are constantly moving forward.  This is especially true as we now ramp up to the version 1.8 release.

Bottom line:  Now is the time to make our mistakes quicker so they don't appear in v1.8.

**Comment by RodneyBaker** [comment]
Will proceed with merging this change with anticipation of additional changes later.
Thank you @andeon for the update.

**Comment by xavier2k6** [comment]
>I have no idea why this CMakeLists.txt file is located in .github/workflows/. Most likely, that file is misplaced.

I found it strange to be there too.....but might be no harm in bumping CMake `min` there until further investigation can be done.

**Comment by andeon** [comment]
> I found it strange to be there too.....but might be no harm in bumping CMake `min` there until further investigation can be done.

Looking through commits, I found it was used in the old `workflow_windows.yml`, but it didn’t work correctly and is causing strange behavior with MyPaintBrushes. The current `workflow_windows.yml` does not use this file anymore. I should have removed it when updating the workflow, but I hadn’t noticed it before. This directory is specifically used for GitHub Actions workflow YAML files, so removing it is safe.

**Comment by shun-iwasawa** [comment]
@andeon 
Sorry for the late comment, but after introducing this PR, it seems that 16bpc TIF images can no longer be loaded correctly. Could you please check if you can reproduce the issue on your end? Also, could you let me know if you have any idea what might be causing it?

image

**Comment by andeon** [comment]
> @andeon Sorry for the late comment, but after introducing this PR, it seems that 16bpc TIF images can no longer be loaded correctly. Could you please check if you can reproduce the issue on your end? Also, could you let me know if you have any idea what might be causing it?

@shun-iwasawa  I suspected this might happen, it's related to a change in tiio_tif.cpp file. I think the issue on macOS may be due to mixing an older TIFF library with another one from Homebrew, and possibly other compatibility issues, especially since macOS 13 is becoming deprecated.That said, the build is no longer blocked.

I'm going to revert the change. Could you please share the original TIFF file here in the [PR](https://github.com/opentoonz/opentoonz/pull/6144), so we can use it for testing and validate in case the future changes?
