### ISSUE TITLE
Version 1.7.1 requires QT >= 5.10

### ISSUE THREAD

**Issue by morevnaproject** [opentoonz/opentoonz#5508]
### Description

In build instruction (https://github.com/opentoonz/opentoonz/blob/master/doc/how_to_build_linux.md) mentioned that minimal QT version is 5.9, but OpenToonz 1.7.1 fails to build with QT 5.9 -
```
[  3%] Building CXX object tnzcore/CMakeFiles/tnzcore.dir/__/common/tvectorimage/tstroke.cpp.o
/build/packet/linux-64/opentoonz-me/build/opentoonz/toonz/sources/common/tsystem/tsystem.cpp: In member function 'QDateTime TFileStatus::getCreationTime() const':
/build/packet/linux-64/opentoonz-me/build/opentoonz/toonz/sources/common/tsystem/tsystem.cpp:90:21: error: 'const class QFileInfo' has no member named 'birthTime'
   return m_fileInfo.birthTime();
                     ^~~~~~~~~
```

birthTime() function in QFileInfo class is available since QT 5.10 - https://doc.qt.io/qt-5/qfileinfo.html#birthTime

Please update requirements in documentation.

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Linux

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by morevnaproject** [comment]
In fact, building with QT 5.10 not helps.
It gives next error:

```
[  8%] Building CXX object tnzcore/CMakeFiles/tnzcore.dir/__/common/tcore/moc_tthreadp.cpp.o
/build/packet/linux-64/opentoonz-me/build/opentoonz/toonz/sources/common/tvrender/tfont_qt.cpp: In member function 'TPoint TFont::drawChar(QImage&, TPoint&, wchar_t, wchar_t) const':
/build/packet/linux-64/opentoonz-me/build/opentoonz/toonz/sources/common/tvrender/tfont_qt.cpp:177:43: error: 'class QFontMetrics' has no member named 'horizontalAdvance'
     int w = QFontMetrics(m_pimpl->m_font).horizontalAdvance(chars[0]);
                                           ^~~~~~~~~~~~~~~~~
/build/packet/linux-64/opentoonz-me/build/opentoonz/toonz/sources/common/tvrender/tfont_qt.cpp: In member function 'TPoint TFont::getDistance(wchar_t, wchar_t) const':
/build/packet/linux-64/opentoonz-me/build/opentoonz/toonz/sources/common/tvrender/tfont_qt.cpp:240:25: error: 'class QFontMetrics' has no member named 'horizontalAdvance'
   return TPoint(metrics.horizontalAdvance(QChar(firstChar)), 0);
                         ^~~~~~~~~~~~~~~~~
```

QT >= 5.11 required (https://doc.qt.io/qt-5/qfontmetrics.html#horizontalAdvance)

**Comment by morevnaproject** [comment]
After successful build one more issue appeared - the buttons in quit dialog are not responding:
![image](https://github.com/opentoonz/opentoonz/assets/332868/e110cdb4-6463-47aa-90ab-b81bbe6d81ac)

Console shows following error:
```
QObject::connect: No such signal QButtonGroup::idClicked(int)
```

QT docs say `idClicked()` signal is available since QT 5.15 - https://doc.qt.io/qt-5/qbuttongroup.html#idClicked

**Comment by RodneyBaker** [comment]
Great to see you @morevnaproject 

I'm not sure what this same issue looks like if we consider Qt 6.0 and beyond although what you mention suggests a good way forward.  Ideally moving into Qt 6.0 and beyond is where we want to move as that becomes an option.

@manongjohn has been pressing forward in that over at Tahoma2D and running into the various obstacles to moving forward in that move.  He should be able to provide some feedback on how to best move forward.

**Comment by andeon** [comment]
We need to update the build instructions to use Qt5 (5.15 or newer). Since some functions need a newer QT now.

I sent a pull request to generate the artifact correctly, if you could test it I'd appreciate it.
