### ISSUE TITLE
[BUG] 1.8.0 build error

### ISSUE THREAD

**Issue by AlexanderShad** [opentoonz/opentoonz#6940]
Hi

I get an error while building the RPM package.

```sh
[00:01:22] /usr/src/RPM/BUILD/opentoonz-1.8.0/toonz/sources/tnztools/stylepickertool.cpp:324:1: error: control reaches end of non-void function [-Werror=return-type]
[00:01:22]   324 | }
[00:01:22]       | ^
```

In my *.patch I did it like this

```sh
--- toonz/sources/tnztools/stylepickertool.cpp	2026-06-19 11:39:05.000000000 +1100
+++ toonz/sources/tnztools/stylepickertool_a.cpp	2026-06-19 18:37:41.481170565 +1100
@@ -321,6 +321,7 @@
     }
     return true;
   }
+  return true;
 }
 
 /* Check if the organizing operation is available */
```

### OpenToonz Version

1.8

### Operating System

Linux

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by Chantology** [comment]
@AlexanderShad can you try the latest version again? I was able to build it from source

**Comment by AlexanderShad** [comment]
> [@AlexanderShad](https://github.com/AlexanderShad) can you try the latest version again? I was able to build it from source

Hi

I'm can't build 1.8.0 without patch

gcc15

part of log:

```sh
[00:01:21] /usr/src/RPM/BUILD/opentoonz-1.8.0/toonz/sources/tnztools/stylepickertool.h: In function 'void {anonymous}::replaceStyle(const TVectorImageP&, int, int, std::vector<std::pair<int, int> >*, std::vector<std::pair<int, int> >*)':
[00:01:21] /usr/src/RPM/BUILD/opentoonz-1.8.0/toonz/sources/tnztools/stylepickertool.h:80:21: warning: comparison of integer expressions of different signedness: 'int' and 'UINT' {aka 'unsigned int'} [-Wsign-compare]
[00:01:21]    80 |   for (int i = 0; i < vi->getStrokeCount(); ++i) {
[00:01:21]       |                   ~~^~~~~~~~~~~~~~~~~~~~~~
[00:01:21] /usr/src/RPM/BUILD/opentoonz-1.8.0/toonz/sources/tnztools/stylepickertool.h:89:21: warning: comparison of integer expressions of different signedness: 'int' and 'UINT' {aka 'unsigned int'} [-Wsign-compare]
[00:01:21]    89 |   for (int i = 0; i < vi->getRegionCount(); ++i) {
[00:01:21]       |                   ~~^~~~~~~~~~~~~~~~~~~~~~
[00:01:21] /usr/src/RPM/BUILD/opentoonz-1.8.0/toonz/sources/tnztools/stylepickertool.h: In member function 'virtual void {anonymous}::ReplaceStyleUndo::redo() const':
[00:01:21] /usr/src/RPM/BUILD/opentoonz-1.8.0/toonz/sources/tnztools/stylepickertool.h:233:23: warning: loop variable '<structured bindings>' creates a copy from type 'const std::pair<const TFrameId, TTileSetCM32*>' [-Wrange-loop-construct]
[00:01:21]   233 |       for (auto const [fid, tileSet] : m_tileSets) {
[00:01:21]       |                       ^~~~~~~~~~~~~~
[00:01:21] /usr/src/RPM/BUILD/opentoonz-1.8.0/toonz/sources/tnztools/stylepickertool.h:233:23: note: use reference type to prevent copying
[00:01:21]   233 |       for (auto const [fid, tileSet] : m_tileSets) {
[00:01:21]       |                       ^~~~~~~~~~~~~~
[00:01:21]       |                       &
[00:01:21] /usr/src/RPM/BUILD/opentoonz-1.8.0/toonz/sources/tnztools/stylepickertool.h:246:23: warning: loop variable '<structured bindings>' creates a copy from type 'const std::pair<const TFrameId, std::pair<std::vector<std::pair<int, int> >, std::vector<std::pair<int, int> > > >' [-Wrange-loop-construct]
[00:01:21]   246 |       for (auto const [fid, pair] : m_modifiedStrokeRegions) {
[00:01:21]       |                       ^~~~~~~~~~~
[00:01:21] /usr/src/RPM/BUILD/opentoonz-1.8.0/toonz/sources/tnztools/stylepickertool.h:246:23: note: use reference type to prevent copying
[00:01:21]   246 |       for (auto const [fid, pair] : m_modifiedStrokeRegions) {
[00:01:21]       |                       ^~~~~~~~~~~
[00:01:21]       |                       &
[00:01:21] /usr/src/RPM/BUILD/opentoonz-1.8.0/toonz/sources/tnztools/stylepickertool.h: In member function 'virtual void {anonymous}::ReplaceStyleUndo::undo() const':
[00:01:21] /usr/src/RPM/BUILD/opentoonz-1.8.0/toonz/sources/tnztools/stylepickertool.h:262:23: warning: loop variable '<structured bindings>' creates a copy from type 'const std::pair<const TFrameId, TTileSetCM32*>' [-Wrange-loop-construct]
[00:01:21]   262 |       for (auto const [fid, tileSet] : m_tileSets) {
[00:01:21]       |                       ^~~~~~~~~~~~~~
[00:01:21] /usr/src/RPM/BUILD/opentoonz-1.8.0/toonz/sources/tnztools/stylepickertool.h:262:23: note: use reference type to prevent copying
[00:01:21]   262 |       for (auto const [fid, tileSet] : m_tileSets) {
[00:01:21]       |                       ^~~~~~~~~~~~~~
[00:01:21]       |                       &
[00:01:21] /usr/src/RPM/BUILD/opentoonz-1.8.0/toonz/sources/tnztools/stylepickertool.h:270:23: warning: loop variable '<structured bindings>' creates a copy from type 'const std::pair<const TFrameId, std::pair<std::vector<std::pair<int, int> >, std::vector<std::pair<int, int> > > >' [-Wrange-loop-construct]
[00:01:21]   270 |       for (auto const [fid, pair] : m_modifiedStrokeRegions) {
[00:01:21]       |                       ^~~~~~~~~~~
[00:01:21] /usr/src/RPM/BUILD/opentoonz-1.8.0/toonz/sources/tnztools/stylepickertool.h:270:23: note: use reference type to prevent copying
[00:01:21]   270 |       for (auto const [fid, pair] : m_modifiedStrokeRegions) {
[00:01:21]       |                       ^~~~~~~~~~~
[00:01:21]       |                       &
[00:01:21] /usr/src/RPM/BUILD/opentoonz-1.8.0/toonz/sources/tnztools/stylepickertool.h: In function 'void replaceLevelStyle(TXshLevelHandle*, TPaletteHandle*, int, int)':
[00:01:21] /usr/src/RPM/BUILD/opentoonz-1.8.0/toonz/sources/tnztools/stylepickertool.h:325:8: warning: unused variable 'style' [-Wunused-variable]
[00:01:21]   325 |   auto style = palette->getStyle(styleId);
[00:01:21]       |        ^~~~~
[00:01:21] /usr/src/RPM/BUILD/opentoonz-1.8.0/toonz/sources/tnztools/stylepickertool.cpp: In member function 'virtual void StylePickerTool::onActivate()':
[00:01:21] /usr/src/RPM/BUILD/opentoonz-1.8.0/toonz/sources/tnztools/stylepickertool.cpp:71:10: warning: unused variable 'ret' [-Wunused-variable]
[00:01:21]    71 |     bool ret = connect(ph, &TPaletteHandle::paletteSwitched, this,
[00:01:21]       |          ^~~
[00:01:21] /usr/src/RPM/BUILD/opentoonz-1.8.0/toonz/sources/tnztools/stylepickertool.cpp: In member function 'virtual bool StylePickerTool::onPropertyChanged(std::string)':
[00:01:21] /usr/src/RPM/BUILD/opentoonz-1.8.0/toonz/sources/tnztools/stylepickertool.cpp:324:1: error: control reaches end of non-void function [-Werror=return-type]
[00:01:21]   324 | }
[00:01:21]       | ^
[00:01:21] /usr/src/RPM/BUILD/opentoonz-1.8.0/toonz/sources/tnztools/stylepickertool.h: At global scope:
[00:01:21] /usr/src/RPM/BUILD/opentoonz-1.8.0/toonz/sources/tnztools/stylepickertool.h:318:13: warning: 'void replaceLevelStyle(TXshLevelHandle*, TPaletteHandle*, int, int)' defined but not used [-Wunused-function]
[00:01:21]   318 | static void replaceLevelStyle(TXshLevelHandle *levelHandle,
[00:01:21]       |             ^~~~~~~~~~~~~~~~~
[00:01:21] cc1plus: some warnings being treated as errors
[00:01:21] gmake[2]: *** [tnztools/CMakeFiles/tnztools.dir/build.make:827: tnztools/CMakeFiles/tnztools.dir/stylepickertool.cpp.o] Error 1
[00:01:21] gmake[2]: Leaving directory '/usr/src/RPM/BUILD/opentoonz-1.8.0/toonz/sources/x86_64-alt-linux'
[00:01:21] gmake[2]: *** Waiting for unfinished jobs....
```

**Comment by Chantology** [comment]
Thanks @AlexanderShad — confirmed, and your patch is correct. Sorry for the runaround; the reason I couldn't reproduce it is that it depends on the build flags, not the compiler version.

Root cause: StylePickerTool::onPropertyChanged() is declared bool but has code paths that fall off the end without returning — both m_organizePalette success branches, and (most commonly) any other property name, since there's no final return. It was introduced in e79af2f2d ("Feat(StylePicker): Add Replace Style Option"), so it affects 1.8.0 and current master.

Why most people don't hit it: OpenToonz's own CMake sets no -Werror anywhere, so this is just a warning in a plain source build. RPM builds inject -Werror=return-type via the distro %optflags, which promotes it to a hard error. That's the whole difference — it isn't a gcc 15 regression.

I reproduced and verified it here on gcc 16.1.1 by compiling that single translation unit with the project's normal flags plus -Werror=return-type: before the fix, stylepickertool.cpp:324:1: error: control reaches end of non-void function; after, it compiles clean.

I went with moving the existing return out of the else if instead of adding a second one, so all three fall-through paths are covered:
```

     }
-    return true;
   }
+  return true;
 } 
```
This also matches the convention in the sibling tools (e.g. RGBPickerTool::onPropertyChanged returns true unconditionally), and no caller actually uses the return value, so there's no behavioral change.

One question: your log also showed signedness-comparison and unused-variable warnings. Those aren't fatal under -Werror=return-type alone, but if your spec file promotes anything else, could you post the full flags or the next error if the build stops again? I'd like to make sure this is the only blocker for a clean RPM build.

**Comment by Chantology** [comment]
I created #6998 @AlexanderShad  can you maybe check if this is working?

**Comment by AlexanderShad** [comment]
> I created [#6998](https://github.com/opentoonz/opentoonz/pull/6998) [@AlexanderShad](https://github.com/AlexanderShad) can you maybe check if this is working?

Hi

Sorry for the late reply.

Yes, using https://github.com/opentoonz/opentoonz/pull/6998, everything builds fine.
